export default {
  id: "Z2lkOi8vc2hvcGlmeS9DaGVja291dC8zYmQzOGZlZDJkOWUwYjY2OWVhNjY0MTVjNzE0NjkwMj9rZXk9N2MyYTJlMmM3MDA5Nzk4YmI0ZDU1MmU3NDQ4ZmJiNWY=",
  ready: true,
  requiresShipping: true,
  note: null,
  paymentDue: "20.00",
  paymentDueV2: {
    amount: "20.0",
    currencyCode: "USD",
    type: {
      name: "MoneyV2",
      kind: "OBJECT",
      fieldBaseTypes: { amount: "Decimal", currencyCode: "CurrencyCode" },
      implementsNode: false,
    },
  },
  webUrl:
    "https://perche-market-dev.myshopify.com/56087511178/checkouts/3bd38fed2d9e0b669ea66415c7146902?key=7c2a2e2c7009798bb4d552e7448fbb5f",
  orderStatusUrl: null,
  taxExempt: false,
  taxesIncluded: false,
  currencyCode: "USD",
  totalTax: "0.00",
  totalTaxV2: {
    amount: "0.0",
    currencyCode: "USD",
    type: {
      name: "MoneyV2",
      kind: "OBJECT",
      fieldBaseTypes: { amount: "Decimal", currencyCode: "CurrencyCode" },
      implementsNode: false,
    },
  },
  lineItemsSubtotalPrice: {
    amount: "20.0",
    currencyCode: "USD",
    type: {
      name: "MoneyV2",
      kind: "OBJECT",
      fieldBaseTypes: { amount: "Decimal", currencyCode: "CurrencyCode" },
      implementsNode: false,
    },
  },
  subtotalPrice: "20.00",
  subtotalPriceV2: {
    amount: "20.0",
    currencyCode: "USD",
    type: {
      name: "MoneyV2",
      kind: "OBJECT",
      fieldBaseTypes: { amount: "Decimal", currencyCode: "CurrencyCode" },
      implementsNode: false,
    },
  },
  totalPrice: "20.00",
  totalPriceV2: {
    amount: "20.0",
    currencyCode: "USD",
    type: {
      name: "MoneyV2",
      kind: "OBJECT",
      fieldBaseTypes: { amount: "Decimal", currencyCode: "CurrencyCode" },
      implementsNode: false,
    },
  },
  completedAt: null,
  createdAt: "2022-02-18T17:14:50Z",
  updatedAt: "2022-02-18T17:14:50Z",
  email: null,
  discountApplications: [],
  appliedGiftCards: [],
  shippingAddress: null,
  shippingLine: null,
  customAttributes: [
    {
      key: "discounts",
      value: "5YEX84,6T6XCO",
      type: {
        name: "Attribute",
        kind: "OBJECT",
        fieldBaseTypes: { key: "String", value: "String" },
        implementsNode: false,
      },
    },
  ],
  order: null,
  lineItems: [
    {
      id: "Z2lkOi8vc2hvcGlmeS9DaGVja291dExpbmVJdGVtLzQwNjc2NDcwOTQ3OTc4MD9jaGVja291dD0zYmQzOGZlZDJkOWUwYjY2OWVhNjY0MTVjNzE0NjkwMg==",
      title: "TEST SUB",
      variant: {
        id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC80MDY3NjQ3MDk0Nzk3OA==",
        title: "Small / Black",
        price: "10.00",
        priceV2: {
          amount: "10.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: { amount: "Decimal", currencyCode: "CurrencyCode" },
            implementsNode: false,
          },
        },
        presentmentPrices: [
          {
            price: {
              amount: "10.0",
              currencyCode: "USD",
              type: {
                name: "MoneyV2",
                kind: "OBJECT",
                fieldBaseTypes: {
                  amount: "Decimal",
                  currencyCode: "CurrencyCode",
                },
                implementsNode: false,
              },
            },
            compareAtPrice: null,
            type: {
              name: "ProductVariantPricePair",
              kind: "OBJECT",
              fieldBaseTypes: { compareAtPrice: "MoneyV2", price: "MoneyV2" },
              implementsNode: false,
            },
            hasNextPage: false,
            hasPreviousPage: false,
            variableValues: {
              input: {
                lineItems: [
                  {
                    variantId:
                      "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC80MDY3NjQ3MDk0Nzk3OA==",
                    quantity: 1,
                    customAttributes: [
                      { key: "subscription", value: "weekly" },
                    ],
                  },
                  {
                    variantId:
                      "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC80MDY3NjQ3MDk0Nzk3OA==",
                    quantity: 1,
                    customAttributes: [
                      { key: "subscription", value: "2month" },
                    ],
                  },
                ],
                customAttributes: [
                  { key: "discounts", value: "5YEX84,6T6XCO" },
                ],
              },
            },
          },
        ],
        weight: 1,
        available: true,
        sku: "TEST_SUB_SMALL_BLACK",
        compareAtPrice: null,
        compareAtPriceV2: null,
        image: {
          id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMjk0NTA1ODM0NDE1NDY=",
          src: "https://cdn.shopify.com/s/files/1/0560/8751/1178/products/15631.jpg?v=1644428549",
          altText: null,
          width: 680,
          height: 349,
          type: {
            name: "Image",
            kind: "OBJECT",
            fieldBaseTypes: {
              altText: "String",
              height: "Int",
              id: "ID",
              originalSrc: "URL",
              src: "URL",
              width: "Int",
            },
            implementsNode: false,
          },
        },
        selectedOptions: [
          {
            name: "Size",
            value: "Small",
            type: {
              name: "SelectedOption",
              kind: "OBJECT",
              fieldBaseTypes: { name: "String", value: "String" },
              implementsNode: false,
            },
          },
          {
            name: "Color",
            value: "Black",
            type: {
              name: "SelectedOption",
              kind: "OBJECT",
              fieldBaseTypes: { name: "String", value: "String" },
              implementsNode: false,
            },
          },
        ],
        unitPrice: null,
        unitPriceMeasurement: {
          measuredType: null,
          quantityUnit: null,
          quantityValue: 0,
          referenceUnit: null,
          referenceValue: 0,
          type: {
            name: "UnitPriceMeasurement",
            kind: "OBJECT",
            fieldBaseTypes: {
              measuredType: "UnitPriceMeasurementMeasuredType",
              quantityUnit: "UnitPriceMeasurementMeasuredUnit",
              quantityValue: "Float",
              referenceUnit: "UnitPriceMeasurementMeasuredUnit",
              referenceValue: "Int",
            },
            implementsNode: false,
          },
        },
        product: {
          id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzY3NjY1NzkxNTUwODI=",
          handle: "test-sub",
          type: {
            name: "Product",
            kind: "OBJECT",
            fieldBaseTypes: {
              availableForSale: "Boolean",
              createdAt: "DateTime",
              description: "String",
              descriptionHtml: "HTML",
              handle: "String",
              id: "ID",
              images: "ImageConnection",
              onlineStoreUrl: "URL",
              options: "ProductOption",
              productType: "String",
              publishedAt: "DateTime",
              title: "String",
              updatedAt: "DateTime",
              variants: "ProductVariantConnection",
              vendor: "String",
            },
            implementsNode: true,
          },
        },
        type: {
          name: "ProductVariant",
          kind: "OBJECT",
          fieldBaseTypes: {
            availableForSale: "Boolean",
            compareAtPrice: "Money",
            compareAtPriceV2: "MoneyV2",
            id: "ID",
            image: "Image",
            presentmentPrices: "ProductVariantPricePairConnection",
            price: "Money",
            priceV2: "MoneyV2",
            product: "Product",
            selectedOptions: "SelectedOption",
            sku: "String",
            title: "String",
            unitPrice: "MoneyV2",
            unitPriceMeasurement: "UnitPriceMeasurement",
            weight: "Float",
          },
          implementsNode: true,
        },
      },
      quantity: 1,
      customAttributes: [
        {
          key: "subscription",
          value: "weekly",
          type: {
            name: "Attribute",
            kind: "OBJECT",
            fieldBaseTypes: { key: "String", value: "String" },
            implementsNode: false,
          },
        },
      ],
      discountAllocations: [],
      type: {
        name: "CheckoutLineItem",
        kind: "OBJECT",
        fieldBaseTypes: {
          customAttributes: "Attribute",
          discountAllocations: "DiscountAllocation",
          id: "ID",
          quantity: "Int",
          title: "String",
          variant: "ProductVariant",
        },
        implementsNode: true,
      },
      hasNextPage: { value: true },
      hasPreviousPage: false,
      variableValues: {
        input: {
          lineItems: [
            {
              variantId:
                "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC80MDY3NjQ3MDk0Nzk3OA==",
              quantity: 1,
              customAttributes: [{ key: "subscription", value: "weekly" }],
            },
            {
              variantId:
                "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC80MDY3NjQ3MDk0Nzk3OA==",
              quantity: 1,
              customAttributes: [{ key: "subscription", value: "2month" }],
            },
          ],
          customAttributes: [{ key: "discounts", value: "5YEX84,6T6XCO" }],
        },
      },
    },
    {
      id: "Z2lkOi8vc2hvcGlmeS9DaGVja291dExpbmVJdGVtLzQwNjc2NDcwOTQ3OTc4MT9jaGVja291dD0zYmQzOGZlZDJkOWUwYjY2OWVhNjY0MTVjNzE0NjkwMg==",
      title: "TEST SUB",
      variant: {
        id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC80MDY3NjQ3MDk0Nzk3OA==",
        title: "Small / Black",
        price: "10.00",
        priceV2: {
          amount: "10.0",
          currencyCode: "USD",
          type: {
            name: "MoneyV2",
            kind: "OBJECT",
            fieldBaseTypes: { amount: "Decimal", currencyCode: "CurrencyCode" },
            implementsNode: false,
          },
        },
        presentmentPrices: [
          {
            price: {
              amount: "10.0",
              currencyCode: "USD",
              type: {
                name: "MoneyV2",
                kind: "OBJECT",
                fieldBaseTypes: {
                  amount: "Decimal",
                  currencyCode: "CurrencyCode",
                },
                implementsNode: false,
              },
            },
            compareAtPrice: null,
            type: {
              name: "ProductVariantPricePair",
              kind: "OBJECT",
              fieldBaseTypes: { compareAtPrice: "MoneyV2", price: "MoneyV2" },
              implementsNode: false,
            },
            hasNextPage: false,
            hasPreviousPage: false,
            variableValues: {
              input: {
                lineItems: [
                  {
                    variantId:
                      "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC80MDY3NjQ3MDk0Nzk3OA==",
                    quantity: 1,
                    customAttributes: [
                      { key: "subscription", value: "weekly" },
                    ],
                  },
                  {
                    variantId:
                      "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC80MDY3NjQ3MDk0Nzk3OA==",
                    quantity: 1,
                    customAttributes: [
                      { key: "subscription", value: "2month" },
                    ],
                  },
                ],
                customAttributes: [
                  { key: "discounts", value: "5YEX84,6T6XCO" },
                ],
              },
            },
          },
        ],
        weight: 1,
        available: true,
        sku: "TEST_SUB_SMALL_BLACK",
        compareAtPrice: null,
        compareAtPriceV2: null,
        image: {
          id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMjk0NTA1ODM0NDE1NDY=",
          src: "https://cdn.shopify.com/s/files/1/0560/8751/1178/products/15631.jpg?v=1644428549",
          altText: null,
          width: 680,
          height: 349,
          type: {
            name: "Image",
            kind: "OBJECT",
            fieldBaseTypes: {
              altText: "String",
              height: "Int",
              id: "ID",
              originalSrc: "URL",
              src: "URL",
              width: "Int",
            },
            implementsNode: false,
          },
        },
        selectedOptions: [
          {
            name: "Size",
            value: "Small",
            type: {
              name: "SelectedOption",
              kind: "OBJECT",
              fieldBaseTypes: { name: "String", value: "String" },
              implementsNode: false,
            },
          },
          {
            name: "Color",
            value: "Black",
            type: {
              name: "SelectedOption",
              kind: "OBJECT",
              fieldBaseTypes: { name: "String", value: "String" },
              implementsNode: false,
            },
          },
        ],
        unitPrice: null,
        unitPriceMeasurement: {
          measuredType: null,
          quantityUnit: null,
          quantityValue: 0,
          referenceUnit: null,
          referenceValue: 0,
          type: {
            name: "UnitPriceMeasurement",
            kind: "OBJECT",
            fieldBaseTypes: {
              measuredType: "UnitPriceMeasurementMeasuredType",
              quantityUnit: "UnitPriceMeasurementMeasuredUnit",
              quantityValue: "Float",
              referenceUnit: "UnitPriceMeasurementMeasuredUnit",
              referenceValue: "Int",
            },
            implementsNode: false,
          },
        },
        product: {
          id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzY3NjY1NzkxNTUwODI=",
          handle: "test-sub",
          type: {
            name: "Product",
            kind: "OBJECT",
            fieldBaseTypes: {
              availableForSale: "Boolean",
              createdAt: "DateTime",
              description: "String",
              descriptionHtml: "HTML",
              handle: "String",
              id: "ID",
              images: "ImageConnection",
              onlineStoreUrl: "URL",
              options: "ProductOption",
              productType: "String",
              publishedAt: "DateTime",
              title: "String",
              updatedAt: "DateTime",
              variants: "ProductVariantConnection",
              vendor: "String",
            },
            implementsNode: true,
          },
        },
        type: {
          name: "ProductVariant",
          kind: "OBJECT",
          fieldBaseTypes: {
            availableForSale: "Boolean",
            compareAtPrice: "Money",
            compareAtPriceV2: "MoneyV2",
            id: "ID",
            image: "Image",
            presentmentPrices: "ProductVariantPricePairConnection",
            price: "Money",
            priceV2: "MoneyV2",
            product: "Product",
            selectedOptions: "SelectedOption",
            sku: "String",
            title: "String",
            unitPrice: "MoneyV2",
            unitPriceMeasurement: "UnitPriceMeasurement",
            weight: "Float",
          },
          implementsNode: true,
        },
      },
      quantity: 1,
      customAttributes: [
        {
          key: "subscription",
          value: "2month",
          type: {
            name: "Attribute",
            kind: "OBJECT",
            fieldBaseTypes: { key: "String", value: "String" },
            implementsNode: false,
          },
        },
      ],
      discountAllocations: [],
      type: {
        name: "CheckoutLineItem",
        kind: "OBJECT",
        fieldBaseTypes: {
          customAttributes: "Attribute",
          discountAllocations: "DiscountAllocation",
          id: "ID",
          quantity: "Int",
          title: "String",
          variant: "ProductVariant",
        },
        implementsNode: true,
      },
      hasNextPage: false,
      hasPreviousPage: { value: true },
      variableValues: {
        input: {
          lineItems: [
            {
              variantId:
                "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC80MDY3NjQ3MDk0Nzk3OA==",
              quantity: 1,
              customAttributes: [{ key: "subscription", value: "weekly" }],
            },
            {
              variantId:
                "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC80MDY3NjQ3MDk0Nzk3OA==",
              quantity: 1,
              customAttributes: [{ key: "subscription", value: "2month" }],
            },
          ],
          customAttributes: [{ key: "discounts", value: "5YEX84,6T6XCO" }],
        },
      },
    },
  ],
  type: {
    name: "Checkout",
    kind: "OBJECT",
    fieldBaseTypes: {
      appliedGiftCards: "AppliedGiftCard",
      completedAt: "DateTime",
      createdAt: "DateTime",
      currencyCode: "CurrencyCode",
      customAttributes: "Attribute",
      discountApplications: "DiscountApplicationConnection",
      email: "String",
      id: "ID",
      lineItems: "CheckoutLineItemConnection",
      lineItemsSubtotalPrice: "MoneyV2",
      note: "String",
      order: "Order",
      orderStatusUrl: "URL",
      paymentDue: "Money",
      paymentDueV2: "MoneyV2",
      ready: "Boolean",
      requiresShipping: "Boolean",
      shippingAddress: "MailingAddress",
      shippingLine: "ShippingRate",
      subtotalPrice: "Money",
      subtotalPriceV2: "MoneyV2",
      taxExempt: "Boolean",
      taxesIncluded: "Boolean",
      totalPrice: "Money",
      totalPriceV2: "MoneyV2",
      totalTax: "Money",
      totalTaxV2: "MoneyV2",
      updatedAt: "DateTime",
      webUrl: "URL",
    },
    implementsNode: true,
  },
  userErrors: [],
}
