export default {
  gladly_env: "PROD",
  checkout_cart_redirect: "https://try.becausemarket.com",
  type_heading_font: { error: "json not allowed for this object" },
  type_heading_size: 100,
  type_base_font: { error: "json not allowed for this object" },
  type_body_size: 100,
  type_number_font: { error: "json not allowed for this object" },
  type_number_size: 100,
  announcement_bg: "#0AE5DA",
  announcement_text: "#333333",
  color_body_text: "#586272",
  accent_warm: "#197bbd",
  accent_cool: "#586272",
  color_border: "#dfe1e3",
  color_body_light: "#667799",
  color_nav_bg: "#fcfcf4",
  color_nav_text: "#667799",
  color_nav_border: "rgba(0,0,0,0)",
  color_footer_bg: "#667799",
  color_footer_text: "#ffffff",
  color_product_grid: "rgba(0,0,0,0)",
  layout_container_enable: true,
  decoration_style: "decoration-none",
  share_facebook: true,
  share_twitter: false,
  share_pinterest: false,
  social_twitter_link: "",
  social_facebook_link: "https://www.facebook.com/becausemarket",
  social_pinterest_link: "",
  social_instagram_link: "https://www.instagram.com/because_market/?hl=en",
  social_snapchat_link: "",
  social_tumblr_link: "",
  social_youtube_link:
    "https://www.youtube.com/channel/UCg0UStPL8YT7fgJeyGRrAcA",
  social_vimeo_link: "",
  social_home_image: null,
  cart_notes_enable: false,
  cart_show_additional_buttons: false,
  cart_continue_browsing: "/collections/all-incontinence",
  collection_text_alignment: "text-left",
  show_vendow: "hide-vendor",
  image_hover_enable: true,
  tag_sellout: false,
  tag_sale: false,
  tag_new: false,
  tag_new_limit: 14,
  favicon: null,
  checkout_header_image: null,
  checkout_logo_image: null,
  checkout_logo_position: "left",
  checkout_logo_size: "medium",
  checkout_body_background_image: null,
  checkout_body_background_color: "#fff",
  checkout_input_background_color_mode: "white",
  checkout_sidebar_background_image: null,
  checkout_sidebar_background_color: "#fafafa",
  checkout_heading_font:
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'",
  checkout_body_font:
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'",
  checkout_accent_color: "#197bbd",
  checkout_button_color: "#197bbd",
  checkout_error_color: "#e32c2b",
  customer_layout: "customer_area",
}
