export default {
  id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0Lzc4NDA1NTE0MDM3NDU=",
  availableForSale: true,
  createdAt: "2022-09-20T09:01:04Z",
  updatedAt: "2022-11-03T18:59:15Z",
  descriptionHtml:
    '<div class="description">\n<ul class="description-features">\n<li>Sleek, streamlined fit is invisible under clothes</li>\n<li>Discreet core and side guards for optimal absorbency without bulk</li>\n<li>Keep fresh with odor protection technology</li>\n<li>Soft, breathable material is comfortable against the skin</li>\n<li>Carbon-neutral production &amp; recycled packaging</li>\n</ul>\n<div class="accordion-info">\n<div class="entry">\n<div class="entry-title">More Info</div>\n<div class="entry-title"></div>\n<div class="entry-text">\n<p>Test Ultra-soft and absorbent, Premium Maximum Plus looks and fits like regular underwear. Constructed with an advanced absorption core and reinforced side guards, it prevents leaks and quickly moves liquid away from the body while locking in odor to keep you feeling fresh all day. The cloth-like material with breathable panels is soft against the skin, while added spandex throughout creates a sleek, form-fitting silhouette that disappears under clothes. Available in beige and grey, the pad in the beige underwear (sizes S/M, L and XL) is ergonomically designed with a narrower core to comfortably fit women’s bodies. This underwear is latex-free and has tear-away side seams for quick and easy removal.</p>\n<p>We’re excited to announce that this collection is sustainably produced in the US in a carbon-neutral facility with post-consumer recycled packaging.</p>\n<p>Choose this style of underwear if you tend to void a lot of urine at once. Absorbs up to 4 cups of liquid.</p>\n</div>\n</div>\n<div class="entry">\n<div class="entry-title">How To Use</div>\n<div class="entry-text">\n<p>Use in place of regular underwear to absorb urine leaks. Slip on, slip off or tear sides for easy disposal.</p>\n</div>\n</div>\n<div class="entry">\n<div class="entry-title">Shipping &amp; Returns</div>\n<div class="entry-text">\n<p>Standard delivery is 7 days on average through FedEx SmartPost. Shorter for metropolitan areas, longer for more rural areas. You will receive a shipping confirmation email with tracking information once your order ships.</p>\n<p><meta charset="utf-8"><meta charset="utf-8"><span data-mce-fragment="1">For returns or exchanges please reach out to </span><a href="mailto:help@becausemarket.com" data-mce-fragment="1" data-mce-href="mailto:help@becausemarket.com" target="_blank">help@becausemarket.com</a><span data-mce-fragment="1">. Returned items are accepted up to 30 days after the shipment arrived. must be in new and unopened condition and you will be responsible for the cost of shipping the items back to us. Refunds will be issued to the original form of payment only, less the handling fee if applicable, within 10 business days after receipt and inspection of the returned product. Returns sent without prior authorization may not be accepted.</span><br></p>\n</div>\n</div>\n</div>\n</div>',
  description:
    "Sleek, streamlined fit is invisible under clothes Discreet core and side guards for optimal absorbency without bulk Keep fresh with odor protection technology Soft, breathable material is comfortable against the skin Carbon-neutral production & recycled packaging More Info Test Ultra-soft and absorbent, Premium Maximum Plus looks and fits like regular underwear. Constructed with an advanced absorption core and reinforced side guards, it prevents leaks and quickly moves liquid away from the body while locking in odor to keep you feeling fresh all day. The cloth-like material with breathable panels is soft against the skin, while added spandex throughout creates a sleek, form-fitting silhouette that disappears under clothes. Available in beige and grey, the pad in the beige underwear (sizes S/M, L and XL) is ergonomically designed with a narrower core to comfortably fit women’s bodies. This underwear is latex-free and has tear-away side seams for quick and easy removal. We’re excited to announce that this collection is sustainably produced in the US in a carbon-neutral facility with post-consumer recycled packaging. Choose this style of underwear if you tend to void a lot of urine at once. Absorbs up to 4 cups of liquid. How To Use Use in place of regular underwear to absorb urine leaks. Slip on, slip off or tear sides for easy disposal. Shipping & Returns Standard delivery is 7 days on average through FedEx SmartPost. Shorter for metropolitan areas, longer for more rural areas. You will receive a shipping confirmation email with tracking information once your order ships. For returns or exchanges please reach out to help@becausemarket.com. Returned items are accepted up to 30 days after the shipment arrived. must be in new and unopened condition and you will be responsible for the cost of shipping the items back to us. Refunds will be issued to the original form of payment only, less the handling fee if applicable, within 10 business days after receipt and inspection of the returned product. Returns sent without prior authorization may not be accepted.",
  handle: "09-20-because-classic-underwear",
  productType: "Underwear",
  title: "09/20 Because Classic Underwear: Updated",
  vendor: "becausemarket-dev",
  publishedAt: "2022-09-20T16:35:54Z",
  onlineStoreUrl:
    "https://dev.store2.becausemarket.com/products/09-20-because-classic-underwear",
  priceRange: {
    minVariantPrice: { amount: "200.0", currencyCode: "USD" },
    maxVariantPrice: { amount: "200.0", currencyCode: "USD" },
  },
  metafields: [
    { namespace: "yotpo", key: "product_id", value: "4862323425350" },
    { namespace: "subscription", key: "daily", value: "10" },
    { namespace: "weekly_offer", key: "discount", value: "10" },
    {
      namespace: "weekly_offer",
      key: "expiry_date",
      value: "2022-10-25T22:30:00Z",
    },
    { namespace: "subscription", key: "monthly", value: "20" },
    {
      namespace: "weekly_offer",
      key: "description",
      value:
        "Test Ultra-soft and absorbent, Premium Maximum Plus looks and fits like regular underwear. Constructed with an advanced absorption core and reinforced side guards, it prevents leaks and quickly moves liquid away from the body while locking in odor to keep you feeling fresh all day. The cloth-like material with breathable panels is soft against the skin, while added spandex throughout creates a sleek, form-fitting silhouette that disappears under clothes. Available in beige and grey, the pad in the beige underwear (sizes S/M, L and XL) is ergonomically designed with a narrower core to comfortably fit women’s bodies. This underwear is latex-free and has tear-away side seams for quick and easy removal.",
    },
  ],
  tags: ["BuyNow"],
  options: [
    {
      id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0T3B0aW9uLzk5NzAxMzE1MDEyODE=",
      name: "Color",
      values: ["Black", "White"],
    },
    {
      id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0T3B0aW9uLzk5NTIzNTkwODgzNTM=",
      name: "Select Pack Size",
      values: ["20", "30"],
    },
  ],
  images: [
    {
      id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMzgzMDA4MzI3OTI4MDE=",
      src: "https://cdn.shopify.com/s/files/1/0651/5048/4705/products/PremiumMaximumPlusUnderwearforWomen-Beige_1080x_e7d789aa-d2ad-4e53-bce9-568a0d51615c.webp?v=1663691720",
      altText: null,
      width: 1080,
      height: 1080,
    },
    {
      id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMzgzNDA1NTcyNDI1OTM=",
      src: "https://cdn.shopify.com/s/files/1/0651/5048/4705/products/NAT_MAX_1080x_a4b592d8-871d-408e-96a7-53dac6628c32.webp?v=1663957486",
      altText: null,
      width: 1000,
      height: 1000,
    },
    {
      id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMzgzNDA1NTcxNzcwNTc=",
      src: "https://cdn.shopify.com/s/files/1/0651/5048/4705/products/Premium-Maximum-Plus-for-Women-3rd_1080x_7e2e1741-4dcc-4778-a24a-d6916f25c0ec.webp?v=1663957486",
      altText: null,
      width: 1000,
      height: 1000,
    },
    {
      id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMzgzNDA1NTcxMTE1MjE=",
      src: "https://cdn.shopify.com/s/files/1/0651/5048/4705/products/Premium-Maximum-Plus-for-Women-5th_1080x_57ee9b05-dc8a-4883-bfc9-ac0979a3619e.webp?v=1663957486",
      altText: null,
      width: 1000,
      height: 1000,
    },
    {
      id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMzgzNDA1NTcxNDQyODk=",
      src: "https://cdn.shopify.com/s/files/1/0651/5048/4705/products/PremiumMaximumPlusforWomen-4th_1080x_d4363d53-c993-44f4-8c0c-072e04d9a051.webp?v=1663957486",
      altText: null,
      width: 1080,
      height: 1080,
    },
    {
      id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMzgzNDA1NTcwNzg3NTM=",
      src: "https://cdn.shopify.com/s/files/1/0651/5048/4705/products/Size-chart_1_1080x_fe07a144-b5a6-47f3-a759-602b597df934.webp?v=1663957486",
      altText: null,
      width: 1080,
      height: 1080,
    },
    {
      id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMzgzNDA1NjExNDE5ODU=",
      src: "https://cdn.shopify.com/s/files/1/0651/5048/4705/products/Size-chart_1_1080x_de61cb0f-3967-4202-83c6-febdfce0d980.webp?v=1663957534",
      altText: null,
      width: 1080,
      height: 1080,
    },
    {
      id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMzgzNDA1NjExMDkyMTc=",
      src: "https://cdn.shopify.com/s/files/1/0651/5048/4705/products/Premium-Maximum-Plus-for-Women-5th_1080x_e5339db0-21b9-4540-b91e-8469383fa1ec.webp?v=1663957534",
      altText: null,
      width: 1000,
      height: 1000,
    },
    {
      id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMzgzNDA1NjA4NDcwNzM=",
      src: "https://cdn.shopify.com/s/files/1/0651/5048/4705/products/PremiumMaximumPlusforWomen-4th_1080x_e234aa7e-dc38-4ca5-a8fc-e81bd284f7f0.webp?v=1663957533",
      altText: null,
      width: 1080,
      height: 1080,
    },
  ],
  variants: [
    {
      id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC80MzMxOTA4MzkyNTcyOQ==",
      title: "Black / 20",
      price: "200.00",
      price: { amount: "200.0", currencyCode: "USD" },
      weight: 0,
      available: true,
      sku: "09/20 Because Classic Underwear 20-pack",
      compareAtPrice: null,
      compareAtprice: null,
      image: {
        id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMzgzMDA4MzI3OTI4MDE=",
        src: "https://cdn.shopify.com/s/files/1/0651/5048/4705/products/PremiumMaximumPlusUnderwearforWomen-Beige_1080x_e7d789aa-d2ad-4e53-bce9-568a0d51615c.webp?v=1663691720",
        altText: null,
        width: 1080,
        height: 1080,
      },
      selectedOptions: [
        { name: "Color", value: "Black" },
        { name: "Select Pack Size", value: "20" },
      ],
      unitPrice: null,
      unitPriceMeasurement: {
        measuredType: null,
        quantityUnit: null,
        quantityValue: 0,
        referenceUnit: null,
        referenceValue: 0,
      },
    },
    {
      id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC80MzM2Mzc1ODM0MjM2OQ==",
      title: "White / 30",
      price: "180.00",
      price: { amount: "180.0", currencyCode: "USD" },
      weight: 0,
      available: true,
      sku: "",
      compareAtPrice: null,
      compareAtprice: null,
      image: {
        id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0SW1hZ2UvMzgzMDA4MzI3OTI4MDE=",
        src: "https://cdn.shopify.com/s/files/1/0651/5048/4705/products/PremiumMaximumPlusUnderwearforWomen-Beige_1080x_e7d789aa-d2ad-4e53-bce9-568a0d51615c.webp?v=1663691720",
        altText: null,
        width: 1080,
        height: 1080,
      },
      selectedOptions: [
        { name: "Color", value: "White" },
        { name: "Select Pack Size", value: "30" },
      ],
      unitPrice: null,
      unitPriceMeasurement: {
        measuredType: null,
        quantityUnit: null,
        quantityValue: 0,
        referenceUnit: null,
        referenceValue: 0,
      },
    },
  ],
}
