export default {
  id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0Lzc4NjEzMDk3MDIzNjk=",
  availableForSale: true,
  createdAt: "2022-10-03T19:01:34Z",
  updatedAt: "2022-10-10T20:55:17Z",
  descriptionHtml: "",
  description: "",
  handle: "10-3-because-premium-maximum-plus-underwear-for-men",
  productType: "",
  title: "10/3 Because Premium Maximum Plus Underwear for Men",
  vendor: "Drylock",
  publishedAt: "2022-10-07T17:20:35Z",
  onlineStoreUrl:
    "https://dev.store2.becausemarket.com/products/10-3-because-premium-maximum-plus-underwear-for-men",
  priceRange: {
    minVariantPrice: { amount: "18.44", currencyCode: "USD" },
    maxVariantPrice: { amount: "23.55", currencyCode: "USD" },
  },
  metafields: [
    { namespace: "yotpo", key: "product_id", value: "4862323425350" },
  ],
  options: [
    {
      id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0T3B0aW9uLzk5Nzg0NjEzNTYyNTc=",
      name: "Size",
      values: [
        "Large (38-50 in)",
        "Small/Medium (28-40 in)",
        "X-Large (48-64 in)",
        "XX-Large (68-80 in)",
      ],
    },
    {
      id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0T3B0aW9uLzk5ODU4ODg4MTMyODE=",
      name: "Select Pack Size",
      values: ["20", "10"],
    },
  ],
  images: [],
  variants: [
    {
      id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC80MzQxMDAwNDE0ODQ0OQ==",
      title: "Large (38-50 in) / 20",
      price: "18.44",
      price: { amount: "18.44", currencyCode: "USD" },
      weight: 0,
      available: true,
      sku: "",
      compareAtPrice: null,
      compareAtprice: null,
      image: null,
      selectedOptions: [
        { name: "Size", value: "Large (38-50 in)" },
        { name: "Select Pack Size", value: "20" },
      ],
      unitPrice: null,
      unitPriceMeasurement: {
        measuredType: null,
        quantityUnit: null,
        quantityValue: 0,
        referenceUnit: null,
        referenceValue: 0,
      },
    },
    {
      id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC80MzQxMDAwNDE4MTIxNw==",
      title: "Small/Medium (28-40 in) / 20",
      price: "18.44",
      price: { amount: "18.44", currencyCode: "USD" },
      weight: 0,
      available: true,
      sku: "",
      compareAtPrice: null,
      compareAtprice: null,
      image: null,
      selectedOptions: [
        { name: "Size", value: "Small/Medium (28-40 in)" },
        { name: "Select Pack Size", value: "20" },
      ],
      unitPrice: null,
      unitPriceMeasurement: {
        measuredType: null,
        quantityUnit: null,
        quantityValue: 0,
        referenceUnit: null,
        referenceValue: 0,
      },
    },
    {
      id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC80MzQxMDAwNDIxMzk4NQ==",
      title: "X-Large (48-64 in) / 20",
      price: "18.44",
      price: { amount: "18.44", currencyCode: "USD" },
      weight: 0,
      available: true,
      sku: "",
      compareAtPrice: null,
      compareAtprice: null,
      image: null,
      selectedOptions: [
        { name: "Size", value: "X-Large (48-64 in)" },
        { name: "Select Pack Size", value: "20" },
      ],
      unitPrice: null,
      unitPriceMeasurement: {
        measuredType: null,
        quantityUnit: null,
        quantityValue: 0,
        referenceUnit: null,
        referenceValue: 0,
      },
    },
    {
      id: "Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0VmFyaWFudC80MzM4ODI5NzI0ODk5Mw==",
      title: "XX-Large (68-80 in) / 10",
      price: "23.55",
      price: { amount: "23.55", currencyCode: "USD" },
      weight: 0,
      available: true,
      sku: "UUDMMX9XX010",
      compareAtPrice: null,
      compareAtprice: null,
      image: null,
      selectedOptions: [
        { name: "Size", value: "XX-Large (68-80 in)" },
        { name: "Select Pack Size", value: "10" },
      ],
      unitPrice: null,
      unitPriceMeasurement: {
        measuredType: null,
        quantityUnit: null,
        quantityValue: 0,
        referenceUnit: null,
        referenceValue: 0,
      },
    },
  ],
}
